gcc/5.4.0: use 'ucontext_t' instead of 'ucontext', bug #629502
Fixes one of build failures against glibc-2.26:

  ./md-unwind-support.h: In function 'x86_64_fallback_frame_state':
  ./md-unwind-support.h:65:47: error: dereferencing pointer to incomplete type 'struct ucontext'
         sc = (struct sigcontext *) (void *) &uc_->uc_mcontext;
                                                 ^~

Bug: https://bugs.gentoo.org/629502